// SPDX-License-Identifier: AGPL-3.0-or-later
//! `data/board_state.yaml`: the few scalars the runtime asks of each board.

/// THE FEW SCALARS THE RUNTIME ASKS OF A BOARD, and the only part of one that
/// is embedded. See its own header for why the rows are not.
pub(crate) const BOARD_STATE: &str = "data/board_state.yaml";

/// WHAT THE LAST RUN LEFT, read the way the writer below spells it.
///
/// BY LINE, not by a yaml crate: the shape is this program's own output and
/// never anybody's input, so a parser dependency here would be one more thing
/// that can disagree with the writer. Read from DISK rather than from the
/// compiled-in copy, because publish rewrites the file after the binary was
/// built and the cursor has to be the one the last run actually stored.
#[derive(Default, Clone)]
pub(crate) struct BoardRow {
    pub(crate) submissions: usize,
    pub(crate) listed: usize,
    pub(crate) scored_at: usize,
}

pub(crate) fn stored_state() -> std::collections::BTreeMap<String, BoardRow> {
    let mut state: std::collections::BTreeMap<String, BoardRow> = Default::default();
    let text = std::fs::read_to_string(BOARD_STATE).unwrap_or_default();
    let mut cur = String::new();
    for line in text.lines() {
        let t = line.trim_end();
        if let Some(id) = t.strip_prefix("  ").and_then(|x| x.strip_suffix(':')) {
            if !id.starts_with(' ') {
                cur = id.to_string();
                state.entry(cur.clone()).or_default();
            }
        } else if let Some((k, v)) = t.trim().split_once(": ") {
            let n = v.trim().parse::<usize>().unwrap_or(0);
            if let Some(e) = state.get_mut(&cur) {
                match k.trim() {
                    "submissions" => e.submissions = n,
                    "listed" => e.listed = n,
                    "scored_at_epoch_seconds" => e.scored_at = n,
                    _ => {}
                }
            }
        }
    }
    state
}

pub(crate) const BOARD_STATE_HEADER: &str = "# WHAT THE RUNTIME KNOWS ABOUT EACH BOARD — GENERATED by `wfsim-board`.
#
# THE ROWS ARE NOT HERE and must never be. `data/` is compiled into the binary,
# so a board archive under it put every row of every board into the wasm that
# every visitor downloads. The rows live in `site/board/<weapon>.json`, which
# the page FETCHES, and durably in the `scores` table they were published from.
#
# `submissions` paired with the library's own size (`/api/board/pending`) is how
# a STATIC board says how far behind it is. `listed` is every row it scored,
# because every scored row is published — how deep to read is the reader's
# question and the page answers it (docs/BOARD.md).
";

/// Merge this ruler's scalars into the state file, when there is one.
pub(crate) fn record_state(bench_id: &str, submissions: usize, listed: usize) {
    if std::path::Path::new(BOARD_STATE).exists() {
        let mut state = stored_state();
        // WHEN, AND NOT ONLY WHAT. The counts say how far behind the board is in
        // BUILDS; a reader looking at a number wants to know how old it is, and
        // that is the one thing neither the counts nor the fingerprints can
        // say — a fingerprint answers "did an input move", never "when was this
        // measured". Seconds rather than a date because the page does the
        // rendering and a board that should move in hours cannot say "today".
        //
        // A board written before this existed carries 0, which the page reads as
        // "unknown" rather than as 1970.
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_or(0, |d| d.as_secs() as usize);
        state.insert(
            bench_id.to_string(),
            BoardRow { submissions, listed, scored_at: now },
        );
        let mut out = String::from(BOARD_STATE_HEADER);
        out.push_str("boards:
");
        for (id, r) in &state {
            out.push_str(&format!(
                "  {id}:
    submissions: {}
    listed: {}
    scored_at_epoch_seconds: {}
",
                r.submissions, r.listed, r.scored_at,
            ));
        }
        std::fs::write(BOARD_STATE, out).unwrap_or_else(|e| panic!("{BOARD_STATE}: {e}"));
    }
}
