#!/usr/bin/env python3
"""Resolve wfsim data ids -> WFCD image names, write data/assets.yaml.

Images are then served at https://cdn.warframestat.us/img/<imageName> (the same
pipeline overframe-class tools use: DE Public Export processed by WFCD).

Usage:  python scripts/gen_assets.py
Re-run whenever new mods/weapons are added. Misses are written commented so a
human can fill the correct name by hand.
"""
import json
import os
import subprocess
import time
import urllib.parse

API = "https://api.warframestat.us/items/"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def http_get(url):
    """Fetch via curl (respects this environment's proxy, unlike urllib)."""
    try:
        out = subprocess.run(
            ["curl", "-s", "--max-time", "25", url],
            capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=30,
        ).stdout
        return json.loads(out) if out.strip() else None
    except Exception:
        return None


def pretty(mod_id: str) -> str:
    return " ".join(w.capitalize() for w in mod_id.split("_"))


# Hand overrides where the prettified id != the in-game item name.
NAME_OVERRIDES = {
    "dual_toxocyst_incarnon": "Dual Toxocyst",  # same art as the base form
    "ppg": "Primed Pistol Gambit",
}


def ids_from_dir(rel):
    d = os.path.join(ROOT, rel)
    return sorted(f[:-5] for f in os.listdir(d) if f.endswith(".yaml"))


def fetch_image_name(item_id: str):
    name = NAME_OVERRIDES.get(item_id, pretty(item_id))
    data = http_get(API + urllib.parse.quote(name))
    if not isinstance(data, dict) or not data.get("imageName"):
        # Fall back to a search and take an exact (case-insensitive) name hit.
        hits = http_get(API + "search/" + urllib.parse.quote(name))
        if isinstance(hits, list):
            data = next((h for h in hits if h.get("name", "").lower() == name.lower()), None)
    if isinstance(data, dict):
        return data.get("imageName")
    return None


def resolve(ids):
    out, miss = {}, []
    for i in ids:
        img = fetch_image_name(i)
        if img:
            out[i] = img
            print(f"  ok  {i:28} -> {img}")
        else:
            miss.append(i)
            print(f"  MISS {i}")
        time.sleep(0.15)  # be gentle to the API
    return out, miss


def main():
    groups = {
        "weapons": ids_from_dir("data/weapons"),
        "mods": ids_from_dir("data/mods"),
        "arcanes": ids_from_dir("data/arcanes"),
    }
    lines = [
        "# Auto-generated by scripts/gen_assets.py from api.warframestat.us.",
        "# Images: https://cdn.warframestat.us/img/<imageName>",
        "# Regenerate: python scripts/gen_assets.py",
        "",
    ]
    all_miss = {}
    for group, ids in groups.items():
        print(f"[{group}] {len(ids)} ids")
        resolved, miss = resolve(ids)
        all_miss[group] = miss
        lines.append(f"{group}:")
        for k, v in sorted(resolved.items()):
            lines.append(f"  {k}: {v}")
        for k in miss:
            lines.append(f"  # {k}:   # UNRESOLVED — fill the WFCD imageName by hand")
        lines.append("")

    path = os.path.join(ROOT, "data", "assets.yaml")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    total_miss = sum(len(v) for v in all_miss.values())
    print(f"\nwrote {path}")
    print(f"unresolved: {total_miss} -> {all_miss}")


if __name__ == "__main__":
    main()
