"""Every WEAPON-EXCLUSIVE gun mod our roster can equip, from WFCD's export.

A mod that only fits one weapon is invisible to every other check we have: the
mod pools are built from what `data/mods/` contains, so a mod nobody has
transcribed is a mod the builder cannot offer and nothing notices. The Dread's
Unseen Dread and the Latron's Double Tap sat missing that way until someone
looked at a wiki page (owner, 2026-08-13).

THE JOIN IS `compatName` x our weapon names, minus what we already carry by
`internal_name` — never by display name, which WFCD duplicates (AGENTS.md).
`compatName` names the BASE of a family and every variant inherits it, which is
why the Latron's augment lists for the Wraith and the Prime too.

Writes `data/surveys/weapon_exclusive_mods.yaml`, which a test reads and nothing else
does. The survey is the FACT (what exists in game); the test is what stops the
gap growing quietly.

    python scripts/survey_weapon_mods.py
"""
import glob
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXPORT = os.path.join(ROOT, 'vendor/warframe-items/data/json/Mods.json')
OUT = os.path.join(ROOT, 'data/surveys/weapon_exclusive_mods.yaml')
GUN_TYPES = {'Primary Mod', 'Secondary Mod', 'Shotgun Mod'}


def carried():
    """internal_name -> the file that carries it."""
    out = {}
    for p in glob.glob(os.path.join(ROOT, 'data/mods/**/*.yaml'), recursive=True):
        t = io.open(p, encoding='utf-8').read()
        m = re.search(r'^internal_name:\s*(\S+)', t, re.M)
        if m:
            out[m.group(1).strip()] = os.path.relpath(p, ROOT).replace(os.sep, '/')
    return out


def weapon_names():
    out = set()
    for p in glob.glob(os.path.join(ROOT, 'data/weapons/**/*.yaml'), recursive=True):
        t = io.open(p, encoding='utf-8').read()
        m = re.search(r'^name:\s*(.+)$', t, re.M)
        if m:
            out.add(m.group(1).strip().strip('"'))
    return out


def fits(compat, names):
    """Does `compatName` name a weapon we carry, or the base of one?"""
    if not compat:
        return []
    return sorted(n for n in names
                  if n == compat or n.startswith(compat + ' ') or n.endswith(' ' + compat))


def main():
    if not os.path.exists(EXPORT):
        sys.exit('%s missing — run scripts/vendor.py first' % EXPORT)
    mods = json.load(io.open(EXPORT, encoding='utf-8'))
    have, names = carried(), weapon_names()

    rows = []
    for m in mods:
        if m.get('type') not in GUN_TYPES:
            continue
        who = fits(m.get('compatName'), names)
        if not who:
            continue
        rows.append({
            'name': m['name'],
            'compat': m['compatName'],
            'kind': m['type'],
            'internal_name': m.get('uniqueName', ''),
            'carried': have.get(m.get('uniqueName', '')),
            'weapons': who,
        })
    rows.sort(key=lambda r: r['name'])

    miss = [r for r in rows if not r['carried']]
    lines = [
        '# EVERY WEAPON-EXCLUSIVE GUN MOD OUR ROSTER CAN EQUIP.',
        '#',
        '# GENERATED by scripts/survey_weapon_mods.py from WFCD\'s export — read by',
        '# a TEST and by nothing else. Do not hand-edit; re-run the script.',
        '#',
        '# A mod that fits one weapon is invisible to every other check: the pools are',
        '# built from what data/mods/ holds, so one nobody transcribed is one the',
        '# builder cannot offer and nothing notices.',
        '#',
        '# %d of %d carried, %d still to transcribe.' % (len(rows) - len(miss), len(rows), len(miss)),
        'mods:',
    ]
    for r in rows:
        lines.append('  - name: %s' % r['name'])
        lines.append('    compat: %s' % r['compat'])
        lines.append('    kind: %s' % r['kind'])
        lines.append('    internal_name: %s' % r['internal_name'])
        lines.append('    carried: %s' % (r['carried'] or '~'))
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
    print('%s: %d rows, %d carried, %d missing' % (
        os.path.relpath(OUT, ROOT), len(rows), len(rows) - len(miss), len(miss)))
    for r in miss:
        print('   MISSING  %-24s (%s) -> %s' % (r['name'], r['kind'], ', '.join(r['weapons'][:3])))


if __name__ == '__main__':
    main()
