"""Every roster entry's `internal_name`, resolved against DE's own item paths.

THE JOIN KEY IS THE WHOLE CROSS-CHECK. `data/README.md` says the two sources
are joined by `internal_name` == `uniqueName` and NEVER by name, because WFCD
carries stale duplicates sharing a display name. Every weapon yaml written
since then opens with "cross-checked against WFCD warframe-items — 0
disagreements" — and a key that resolves to nothing produces exactly that
sentence, from a comparison that never ran.

It happened: `hema` shipped `/Lotus/Weapons/Infested/InfWFAccompanyingPri/...`
against DE's `/Lotus/Weapons/Infested/LongGuns/InfWFAccompanyingPri/...` —
one path segment short — and every sweep since has silently skipped that weapon
. Nothing could see it, because every sweep asked about the weapons
it could FIND.

So the survey records, per entry id, the `uniqueName` the export actually
holds. `data/surveys/internal_names.yaml` is read by a ratchet test and by
nothing else: the survey is the FACT, the test is what stops a key drifting
quietly. An entry with no `internal_name` at all (a FORM, which inherits its
weapon's) is absent from the survey rather than recorded as a failure — a form
states only what differs from its weapon.

    python scripts/survey_internal_names.py
"""
import glob
import io
import json
import os

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXPORT_DIR = os.path.join(ROOT, 'vendor/warframe-items/data/json')
OUT = os.path.join(ROOT, 'data/surveys/internal_names.yaml')

HEADER = """\
# EVERY ROSTER ENTRY'S `internal_name`, AS DE'S EXPORT SPELLS IT.
#
# Generated by scripts/survey_internal_names.py from vendor/warframe-items.
# Read by `every_internal_name_resolves_in_the_export` and by nothing else.
#
# WHY IT EXISTS. `internal_name` == `uniqueName` is the ONLY join between our
# data and the cross-check source (never the display name — WFCD has stale
# duplicates sharing one). A key with a typo in it does not fail; it MISSES,
# and a miss is indistinguishable from a weapon nobody has cross-checked. The
# Hema carried a path one segment short from the day it was written and every
# sweep since skipped it in silence.
#
# Entries with no `internal_name` are FORMS, which inherit their weapon's, and
# are absent here rather than recorded as gaps.
#
# Regenerate after adding weapons; a new entry whose key resolves to nothing is
# a transcription error in the entry, not a gap in this file.
"""


def export_unique_names():
    names = set()
    for path in sorted(glob.glob(os.path.join(EXPORT_DIR, '*.json'))):
        with io.open(path, encoding='utf-8') as fh:
            try:
                items = json.load(fh)
            except ValueError:
                continue
        if not isinstance(items, list):
            continue
        for item in items:
            if isinstance(item, dict) and item.get('uniqueName'):
                names.add(item['uniqueName'])
    return names


def main():
    if not os.path.isdir(EXPORT_DIR):
        raise SystemExit(
            'vendor/warframe-items is not present — run scripts/vendor.py first'
        )
    known = export_unique_names()
    if not known:
        raise SystemExit('the export holds no uniqueName at all — refusing to write')

    resolved, missing = {}, []
    for path in sorted(glob.glob(os.path.join(ROOT, 'data/weapons/*/*.yaml'))):
        with io.open(path, encoding='utf-8') as fh:
            spec = yaml.safe_load(fh)
        key = spec.get('internal_name')
        if not key:
            continue
        if key in known:
            resolved[spec['id']] = key
        else:
            missing.append((spec['id'], key))

    if missing:
        for wid, key in missing:
            print('UNRESOLVED  %-24s %s' % (wid, key))
        raise SystemExit(
            '%d entry/entries carry an internal_name the export does not hold. '
            'Fix the entry — the survey records what IS, and refuses to record '
            'a key that joins to nothing.' % len(missing)
        )

    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(HEADER)
        fh.write('\nresolved:\n')
        for wid in sorted(resolved):
            fh.write('  %-30s %s\n' % (wid + ':', resolved[wid]))
    print('%d entries resolved -> %s' % (len(resolved), os.path.relpath(OUT, ROOT)))


if __name__ == '__main__':
    main()
